name: 'gcloud Container Registry Docker Login (KrashLeviathan fork)'
author: 'Lars Gohr'
branding:
  icon: 'cloud'
  color: 'blue'
description: 'Logs into Google Cloud Container Registry and provides Docker credentials'
inputs:
  account_key:
    description: 'Base64 encoded service account key exported as JSON'
    required: true
outputs:
  username:
    description: 'The username for logging in'
  password:
    description: 'The password for logging in'
runs:
  using: 'docker'
  image: 'Dockerfile'
